name = "RPGPack"
author = "firstlane"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b57d76fd05854bb57930b9010597f38510fe8f1aa36d20decc4984bcdac08561"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
