name = "RPGPack"
author = "firstlane"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "268cac8c9741dbacdd92e85dc31c80864253aa99bf1f4b36c1400f00e6eee98a"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
