name = "RPGPack"
author = "firstlane"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e4632c366adfe3df1ca40ecc4e218334f18828e502e98ffbf105aa2b4a7c400"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
