name = "RPGPack"
author = "firstlane"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b3516eb4339b9ed61206fec609ef11f25b49ecefc4d00731215b297bf4e76ea6"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
