name = "RPGPack"
author = "firstlane"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "504f37b81b5c827ca6218bd6f34745f0742876c4296c940cc1b276c16c283641"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
