name = "RPGPack"
author = "firstlane"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "95add8427f55b0c27b89d6dfbd443bc5ec7082de0441d1ebe00097f47ea537b1"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
