name = "RPGPack"
author = "firstlane"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "74ef56654179d51225b2755dcf7d2ce98dc7df92f64ced73a6232f762b088442"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
