name = "RPGPack"
author = "firstlane"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a51953f2379cfb57437dbe992a33ab7ef9ae2b57409bb3676a12749d3fa85c6"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
