name = "RPGPack"
author = "firstlane"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a520f5330e3bb88e7c59bb1d666912a6ca57201a461af937bed7f4a4145aa44"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
