
#Sword Ability Settings
[abilities]
	#Whether the Fireball ability will destroy blocks with it explodes.
	fireballDestroyBlocks = true
	#The cooldown (in ticks) of the Fireball ability.
	#Range: 0 ~ 10000
	fireballCooldown = 200
	#The maximum amount of charge that a sword can hold.
	#1 unit of charge is used each tick when holding right click.
	#Range: 1 ~ 10000
	vortexChargeCapacity = 400
	#The amount of charge gained per each fully charged hit on a mob.
	#Range: 1 ~ 10000
	vortexChargePerHit = 50
	#The maximum amount of health that the Vampiric ability can heal.
	#Range: 1 ~ 1000
	vampiricHealthCap = 10
	#The chance that you will inflict a status effect on a mob upon hitting it with the Alchemist abiliy.
	#Range: 0.0 ~ 1.0
	alchemistVictimChance = 0.5
	#The increase in power each tick that you use the Fireball ability.
	#Note that the fireball will grow at twice this rate for the first half of the max power.
	#Range: 0.01 ~ 1.0
	fireballChargeRate = 0.04
	#The chance that you will receive a status effect upon killing a mob with the Alchemist abiliy.
	#Range: 0.0 ~ 1.0
	alchemistSelfChance = 0.5
	#The number of hits with a Thunder Smite sword before the sword becomes electrically charged.
	#Range: 1 ~ 10
	thunderSmiteCharges = 3
	#The cooldown (in ticks) of the Toxic Dash ability.
	#Range: 0 ~ 10000
	toxicDashCooldown = 200
	#Whether the Fireball ability will set fire when it explodes.
	fireballSetFire = true
	#The average length of time (in ticks) that the Bat Swarm ability will last.
	#Range: 10 ~ 10000
	batSwarmDuration = 60
	#The average length of time (in ticks) that the Bat Swarm ability will last.
	#Range: 0.0 ~ 100.0
	batSwarmDamage = 2.0
	#The duration (in ticks) that the Ender Rift entity lasts for after creation.
	#Client and server restart required.
	#Range: 10 ~ 200
	enderRiftDuration = 60
	#The maximum power of the Fireball ability.
	#This value must be evenly divisible by fireballChargeRate or else the actual max power could be slightly off.
	#Range: 1.0 ~ 100.0
	fireballMaxPower = 4.0
	#Whether you can use the Double Jump ability while riding a vehicle.
	#This feature is pretty buggy, but also pretty fun.
	doubleJumpVehicle = false
	#The amount of damage dealt to mobs by Vortex Charge's shift-right-click ability.
	#Range: 0.0 ~ 100.0
	vortexChargeDamage = 12.0
	#The cooldown (in ticks) of the Bat Swarm ability.
	#Range: 0 ~ 10000
	batSwarmCooldown = 200
	#The percentage of a killed entity's max health that the Vampiric ability will heal its user.
	#Range: 0.01 ~ 2.0
	vampiricHealthPercent = 0.15
	#The cooldown (in ticks) of the Ender Rift ability.
	#Must be longer than enderRiftDuration.
	#Range: 0 ~ 10000
	enderRiftCooldown = 200

#Sword Stats
[stats]
	#The base attack speed of a sword from this mod.
	#The slowest sword possible will have this for its attack damage.
	#Range: 0.0 ~ 2.0
	baseAttackSpeed = 1.2
	#The amount that swords' attack speeds can vary randomly.
	#The fastest sword possible will have this added to baseAttackSpeed for its attack speed.
	#Range: 0.0 ~ 1.0
	maxAttackSpeedModifier = 0.6
	#The durability of swords from this mod.A value of 0 will cause swords from this mod to be unbreakable.Client and server restart required.
	#Range: 0 ~ 10000
	durability = 2000
	#The amount that swords' attack damages can vary randomly.
	#The strongest sword possible will have this added to baseDamage for its attack damage.
	#Range: 0.0 ~ 50.0
	maxDamageModifier = 2.5
	#The base damage of a sword from this mod.
	#The weakest sword possible will have this for its attack damage.
	#Range: 1 ~ 100
	baseDamage = 6

#Sword Stone Settings
[sword_stone]
	#The minimum distance (in chunks) between sword stones in the End.
	#Must be smaller than swordStoneSpacingEnd.
	#Range: 0 ~ 4096
	swordStoneSeparationEnd = 15
	#Add the ids of sword abilities here to disabled them. Ex. "swordinthestone:thunder_smite"
	disabledAbilities = []
	#The average distance (in chunks) between sword stones in the Nether.
	#Range: 0 ~ 4096
	swordStoneSpacingNether = 35
	#Whether sword stones should show a beacon beam every so often to alert players to their location.
	swordBeaconEnabled = true
	#The average distance (in chunks) between sword stones in the Overworld.
	#Range: 0 ~ 4096
	swordStoneSpacingOverworld = 40
	#The minimum distance (in chunks) between sword stones in the Nether.
	#Must be smaller than swordStoneSpacingNether.
	#Range: 0 ~ 4096
	swordStoneSeparationNether = 10
	#The minimum distance (in chunks) between sword stones in the Overworld.
	#Must be smaller than swordStoneSpacingOverworld.
	#Range: 0 ~ 4096
	swordStoneSeparationOverworld = 15
	#The average distance (in chunks) between sword stones in the End.
	#Range: 0 ~ 4096
	swordStoneSpacingEnd = 40

