name = "RPGPack"
author = "firstlane"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3900a670ffc54135839d568fde2c46248535d2b25af4222f79a7425c7f39adc4"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
