name = "RPGPack"
author = "firstlane"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "97bcfccb537ec96b0d0c4949c40627b73ffeb7928d311204627b07c431a5bd43"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
