name = "RPGPack"
author = "firstlane"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8dfbfde9258f3f6d6a9b44eb9b92966361f55b264a021781454b01a210d963a6"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
