name = "Spooky"
author = "firstlane"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "336e96c3cfb4b291fbd6e1c029319ee655abec16adc9f7c0b6d74f8589680324"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
