name = "Cobblemon"
author = "firstlane"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "393c816e87fab70c928973d459c6ac7bebb2c49ac6d4c66f5ef31e0e1fd41fd8"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
