name = "Cobblemon"
author = "firstlane"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1b1263d751035a7485ea15744c0225836ac88a2613c959e169b8ec75fcde029f"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
