name = "Cobblemon"
author = "firstlane"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b28a50964a2792aa6b92fb6398fd5c62c9f8aad3ba83c7f8cc8981c71dd6622d"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
